[package]
name = "minicom-syntax"
version = "0.1.0"
authors = ["agatan <agatan039@gmail.com>"]
build = "build.rs"

[dependencies]
quick-error = "1.2"
lalrpop-util = "0.13"

minicom-basis = { path = "../basis" }

[build-dependencies]
lalrpop = "0.13"
